name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - scipy
  - numba
  - tqdm
  - pip
  - pip:
      - import_ipynb
      - jupyter
